select U.ERS_USERNAME, U.ERS_PASSWORD, U.USER_FIRST_NAME, U.USER_LAST_NAME, U.USER_EMAIL, R.USER_ROLES
FROM ERS.USERS AS U
INNER JOIN ERS.USER_ROLES AS R
ON U.USER_ROLE_ID = R.ERS_USER_ROLE_ID
WHERE U.ERS_USERNAME = LOWER('LLEVIT');

select U.ERS_USERNAME, U.ERS_PASSWORD, U.USER_FIRST_NAME, U.USER_LAST_NAME, U.USER_EMAIL, R.USER_ROLES
FROM ERS.USERS AS U
INNER JOIN ERS.USER_ROLES AS R
ON U.USER_ROLE_ID = R.ERS_USER_ROLE_ID;

select * from ers.USER_ROLES
