select U.ERS_USERNAME, U.ERS_PASSWORD, U.USER_FIRST_NAME, U.USER_LAST_NAME, U.USER_EMAIL, R.USER_ROLES
FROM ERS.USERS AS U
INNER JOIN ERS.USER_ROLES AS R
ON U.USER_ROLE_ID = R.ERS_USER_ROLE_ID
WHERE U.ERS_USERNAME = LOWER('LLEVIT');

select U.ERS_USERNAME, U.ERS_PASSWORD, U.USER_FIRST_NAME, U.USER_LAST_NAME, U.USER_EMAIL, R.USER_ROLES
FROM ERS.USERS AS U
INNER JOIN ERS.USER_ROLES AS R
ON U.USER_ROLE_ID = R.ERS_USER_ROLE_ID;

select * from ers.USER_ROLES

SELECT U.USER_FIRST_NAME, U.USER_LAST_NAME, R.REIMB_AMMOUNT, T.REIMB_TYPE, R.REIMB_SUBMITTED ,S.REIMB_STATUS
FROM ERS.REIMBURSEMENT AS R
INNER JOIN ERS.USERS AS U
ON R.REIMB_AUTHOR = U.ERS_USERS_ID
INNER JOIN ERS.REIMBURSEMENT_TYPE AS T
ON R.REIMB_TYPE_ID = T.REIMB_TYPE_ID
INNER JOIN ERS.REIMBURSEMENT_STATUS AS S
ON R.REIMB_STATUS_ID = S.REIMB_STATUS_ID;

SELECT R.REIMB_SUBMITTED, T.REIMB_TYPE, R.REIMB_AMMOUNT,  S.REIMB_STATUS
FROM ERS.REIMBURSEMENT AS R
INNER JOIN ERS.USERS AS U
ON R.REIMB_AUTHOR = U.ERS_USERS_ID
INNER JOIN ERS.REIMBURSEMENT_TYPE AS T
ON R.REIMB_TYPE_ID = T.REIMB_TYPE_ID
INNER JOIN ERS.REIMBURSEMENT_STATUS AS S
ON R.REIMB_STATUS_ID = S.REIMB_STATUS_ID;
