--selects a specific user by username
SELECT U.ERS_USERS_ID, U.ERS_USERNAME, U.ERS_PASSWORD,
U.USER_FIRST_NAME, U.USER_LAST_NAME, U.USER_EMAIL, R.USER_ROLES
FROM ERS.USERS AS U
INNER JOIN ERS.USER_ROLES AS R
ON U.USER_ROLE_ID = R.ERS_USER_ROLE_ID
WHERE U.ERS_USERNAME = LOWER('LLEVIT');

--selects all reimbursements from a specific user
SELECT R.REIMB_ID, R.REIMB_SUBMITTED, E.USER_FIRST_NAME, 
E.USER_LAST_NAME, T.REIMB_TYPE, R.REIMB_AMOUNT, 
R.REIMB_DESCRIPTION ,S.REIMB_STATUS, R.REIMB_RESOLVED, 
M.USER_FIRST_NAME, M.USER_LAST_NAME 
FROM ERS.REIMBURSEMENT AS R
JOIN ERS.USERS AS E
ON R.REIMB_AUTHOR = E.ERS_USERS_ID
JOIN ERS.REIMBURSEMENT_TYPE AS T
ON R.REIMB_TYPE_ID = T.REIMB_TYPE_ID
JOIN ERS.REIMBURSEMENT_STATUS AS S
ON R.REIMB_STATUS_ID = S.REIMB_STATUS_ID
LEFT JOIN ERS.USERS AS M
ON R.REIMB_RESOLVER = M.ERS_USERS_ID
WHERE E.ERS_USERNAME = LOWER('LLEVIT');

--selects all reimbursements from all users
SELECT R.REIMB_ID, R.REIMB_SUBMITTED, E.USER_FIRST_NAME, 
E.USER_LAST_NAME, T.REIMB_TYPE, R.REIMB_AMOUNT, 
R.REIMB_DESCRIPTION, S.REIMB_STATUS, R.REIMB_RESOLVED, 
M.USER_FIRST_NAME, M.USER_LAST_NAME 
FROM ERS.REIMBURSEMENT AS R
JOIN ERS.USERS AS E
ON R.REIMB_AUTHOR = E.ERS_USERS_ID
JOIN ERS.REIMBURSEMENT_TYPE AS T
ON R.REIMB_TYPE_ID = T.REIMB_TYPE_ID
JOIN ERS.REIMBURSEMENT_STATUS AS S
ON R.REIMB_STATUS_ID = S.REIMB_STATUS_ID
LEFT JOIN ERS.USERS AS M
ON R.REIMB_RESOLVER = M.ERS_USERS_ID;

--inserts a new reimbursement from a specific user
INSERT INTO ERS.REIMBURSEMENT (REIMB_AMOUNT, REIMB_SUBMITTED,
REIMB_DESCRIPTION, REIMB_AUTHOR, REIMB_STATUS_ID, REIMB_TYPE_ID)
SELECT 2400, '2019-03-31 12:07:15', 'Totally justified', 2,
S.REIMB_STATUS_ID, T.REIMB_TYPE_ID
FROM ERS.REIMBURSEMENT_STATUS AS S, ERS.REIMBURSEMENT_TYPE AS T
WHERE S.REIMB_STATUS = 'Pending' AND T.REIMB_TYPE = 'Travel';

--updates reimbursement status
UPDATE ERS.REIMBURSEMENT
SET  REIMB_RESOLVED = '2019-04-01 09:56:00', 
REIMB_RESOLVER = 1, REIMB_STATUS_ID = S.REIMB_STATUS_ID 
FROM ERS.REIMBURSEMENT_STATUS AS S
WHERE REIMB_ID = '2' AND S.REIMB_STATUS = 'Approved';

SELECT * FROM ERS.REIMBURSEMENT;
SELECT * FROM ERS.USERS;

sp_help 'ERS.REIMBURSEMENT';
sp_help 'ERS.USERS';