CREATE DATABASE ERS;
GO
CREATE SCHEMA ERS;
GO
CREATE TABLE ERS.USER_ROLES (
	ERS_USER_ROLE_ID SMALLINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	USER_ROLES VARCHAR(10) NOT NULL
);
GO
CREATE TABLE ERS.USERS (
	ERS_USERS_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ERS_USERNAME VARCHAR(50) NOT NULL UNIQUE,
	ERS_PASSWORD VARCHAR(50) NOT NULL,
	USER_FIRST_NAME VARCHAR(100) NOT NULL,
	USER_LAST_NAME VARCHAR(100) NOT NULL,
	USER_EMAIL VARCHAR(150) NOT NULL UNIQUE,
	USER_ROLE_ID SMALLINT NOT NULL FOREIGN KEY 
			REFERENCES ERS.USER_ROLES(ERS_USER_ROLE_ID)
);
GO
CREATE TABLE ERS.REIMBURSEMENT_STATUS (
	REIMB_STATUS_ID SMALLINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	REIMB_STATUS VARCHAR(10)
);
GO
CREATE TABLE ERS.REIMBURSEMENT_TYPE (
	REIMB_TYPE_ID SMALLINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	REIMB_TYPE VARCHAR(10)
);
GO
CREATE TABLE ERS.REIMBURSEMENT (
	REIMB_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	REIMB_AMMOUNT DECIMAL(10, 2) NOT NULL,
	REIMB_SUBMITTED DATETIME NOT NULL,
	REIMB_RESOLVED DATETIME,
	REIMB_DESCRIPTION VARCHAR(250),
	REIMB_RECEIPT IMAGE,
	REIMB_AUTHOR INT NOT NULL FOREIGN KEY 
			REFERENCES ERS.USERS(ERS_USERS_ID),
	REIMB_RESOLVER INT FOREIGN KEY 
			REFERENCES ERS.USERS(ERS_USERS_ID),
	REIMB_STATUS_ID SMALLINT NOT NULL 
			FOREIGN KEY REFERENCES ERS.REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
	REIMB_TYPE_ID SMALLINT NOT NULL 
			FOREIGN KEY REFERENCES ERS.REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);
GO
INSERT INTO ERS.USER_ROLES (USER_ROLES)
VALUES
('EMPLOYEE'), ('FI_MANAGER');
GO
INSERT INTO ERS.REIMBURSEMENT_STATUS (REIMB_STATUS)
VALUES
('PENDING'),('APPROVED'),('DENIED');
GO
INSERT INTO ERS.REIMBURSEMENT_TYPE (REIMB_TYPE)
VALUES
('LODGING'),('TRAVEL'),('FOOD'),('TRAINING'),
('SUPPLIES'),('MEDICAL'),('OTHER');
GO
INSERT INTO ERS.USERS (ERS_USERNAME, ERS_PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_ROLE_ID)
VALUES
('gbonds','gen123','Genesis','Bonds','genesis.bonds@revature.com', 2),
('llevit','lev123','Lev', 'Levit', 'levlevit@gmail.com', 1),
('aanton','alek123','Aleksandr','Antonov','alekzandar@live.com',1),
('ashush','alex123','Aleksandr','Shushunov','a.v.shushunov@gmail.com',1),
('aaraf','amro123','Amro','Arafat','amroarafat84@gmail.com',1),
('dwhite','dav123','David','White-Goode','goodescientist@gmail.com',1),
('ghadj','greg123','Gregory','Hadjiyane','ghadji@optonline.net',1),
('mreyes','mar123','Maressa','Reyes','maritza10546@hotmail.com',1),
('mleclair','mat123','Matthew','LeClair','leclair.matt1@gmail.com',1),
('smineo','sim123','Simone','Mineo','simone.mineo424@gmail.com',1),
('slo','ste123','Stephen','Lo','lo.stephen.j@gmail.com',1),
('tnawshin','taw123','Tawbin','Nawshin','tawbin.nawshin@gmail.com',1),
('twest','tif123','Tiffany','West','tiffanywest520@gmail.com',1),
('junk','jac123','Jacky','Unknown','iapchi86@gmail.com',1);
GO
INSERT INTO ERS.REIMBURSEMENT (REIMB_AMMOUNT, REIMB_SUBMITTED, REIMB_AUTHOR, REIMB_STATUS_ID, REIMB_TYPE_ID)
VALUES
(250.00, '2019-03-24 12:08:30', 2, 1, 4);

--DELETE FROM ERS.REIMBURSEMENT_TYPE;
--DBCC CHECKIDENT ('ERS.REIMBURSEMENT_TYPE', RESEED, 0);
--SELECT * FROM ERS.USER_ROLES;
--SELECT * FROM ERS.REIMBURSEMENT_STATUS;
--SELECT * FROM ERS.REIMBURSEMENT_TYPE;
--SELECT * FROM ERS.USERS;
--SELECT * FROM ERS.REIMBURSEMENT;